apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2 # You can adjust the number of replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
--- # Separator for multiple resources in a single file
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: ngi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP # Or NodePort, LoadBalancer, depending on your needs
