apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: failed-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: non-existent-storage-class # Intentionally incorrect storage class
